# Generated by Django 6.0.6 on 2026-07-03 07:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plans", "0002_planaccess"),
        ("products", "0003_product_is_digital"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="plans.plan",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("plan__isnull", False), ("product__isnull", True)
                            ),
                            models.Q(
                                ("plan__isnull", True), ("product__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="review_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("plan__isnull", False)),
                        fields=("user", "plan"),
                        name="uniq_review_user_plan",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("product__isnull", False)),
                        fields=("user", "product"),
                        name="uniq_review_user_product",
                    ),
                ],
            },
        ),
    ]
