# Generated by Django 6.0.6 on 2026-07-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_image_product_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_digital",
            field=models.BooleanField(default=False),
        ),
    ]
